#!/bin/bash

riscv_gxx="$(which riscv-g++ 2> /dev/null)"
riscv64_elf_gxx="$(which riscv64-unknown-elf-g++ 2> /dev/null)"
riscv64_linux_gxx="$(which riscv64-unknown-linux-gnu-g++ 2> /dev/null)"

cxx="$(echo $riscv64_linux_gxx $riscv64_elf_gxx $riscv_gxx | cut -d' ' -f1)"
if [[ "$cxx" == "" ]]
then
    echo "No RISC-V cross compiler detected, compiling natively" >&2
    exit 0
fi

$cxx -mhwachav4 -x c++ /dev/null -E >& /dev/null
if [[ "$?" == "0" ]]
then
    hwacha_opts="-mhwacha4"
else
    hwacha_opts="-D__riscv_hwacha3"
fi

cat <<EOF
LANGUAGES += c++
COMPILER = $cxx
LINKER = $cxx
COMPILEOPTS += -Wa,-march=RVIMAFDXhwacha $hwacha_opts
EOF
